version: "3.9"
services:
  mongo-container:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./store/v1/data:/data/db
      - ./store/v1/config:/data/configdb
  search-app:
    build: .
    ports:
      - "4000:4000"